### ISSUE TITLE
Segmentation fault when creatSession

### ISSUE THREAD

**Issue by olongo** [Hanson0910/MNNSuperGlue#5]
运行的时候，执行到SuperPoint的构造函数的this->session = this->net->createSession(this->config);这句报段错误，请问要怎么解决

**Comment by Hanson0910** [comment]
是不是模型路径有问题，有绝对路径。


| |
Hanson
|
|
***@***.***
|
签名由网易邮箱大师定制
On 1/5/2022 ***@***.***> wrote：

运行的时候，执行到SuperPoint的构造函数的this->session = this->net->createSession(this->config);这句报段错误，请问要怎么解决

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by olongo** [comment]
模型路径没问题，SuperGlue和L2Norm都可以构造，而且路径有问题的话会报另一个错
方便的话，可以给个方便点的联系方式嘛，还有些其他问题想请教一下

这是gdb的调试信息：
(gdb) bt
#0  0x00007ffff63bda23 in __memmove_avx_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:233
#1  0x00007ffff7b1e1a3 in std::_Function_handler<void (int), MNN::ConvolutionWinograd::onExecute(std::vector<MNN::Tensor*, std::allocator<MNN::Tensor*> > const&, std::vector<MNN::Tensor*, std::allocator<MNN::Tensor*> > const&)::{lambda(int)#2}>::_M_invoke(std::_Any_data const&, int&&) ()
    at /home/white/ThirdLibrary/MNN-master/build/libMNN.so
#2  0x00007ffff7affb0f in MNN::ThreadPool::enqueue(std::pair<std::function<void (int)>, int>&&, int) () at /home/white/ThirdLibrary/MNN-master/build/libMNN.so
#3  0x00007ffff7b1f320 in MNN::ConvolutionWinograd::onExecute(std::vector<MNN::Tensor*, std::allocator<MNN::Tensor*> > const&, std::vector<MNN::Tensor*, std::allocator<MNN::Tensor*> > const&) ()
    at /home/white/ThirdLibrary/MNN-master/build/libMNN.so
#4  0x00007ffff7a0f068 in MNN::GeometryComputerUtils::shapeComputeAndGeometryTransform(std::vector<MNN::Schedule::PipelineInfo, std::allocator<MNN::Schedule::PipelineInfo> >&, MNN::GeometryComputer::Context&, std::shared_ptr<MNN::Backend>, MNN::Runtime::CompilerType) ()
    at /home/white/ThirdLibrary/MNN-master/build/libMNN.so
#5  0x00007ffff79db9cc in MNN::Pipeline::encode(bool, bool) ()
    at /home/white/ThirdLibrary/MNN-master/build/libMNN.so
#6  0x00007ffff79e31b7 in MNN::Session::resize(bool) ()
    at /home/white/ThirdLibrary/MNN-master/build/libMNN.so
#7  0x00007ffff79cb315 in MNN::Interpreter::createMultiPathSession(std::vector<M----Typ---Type <r---Type <r---T---T---Type <---T-------Type <return> to continue, or q <return> to quit---
NN::ScheduleConfig, std::allocator<MNN::ScheduleConfig> > const&, std::pair<std::map<MNNForwardType, std::shared_ptr<MNN::Runtime>, std::less<MNNForwardType>, std::allocator<std::pair<MNNForwardType const, std::shared_ptr<MNN::Runtime> > > >, std::shared_ptr<MNN::Runtime> > const&) () at /home/white/ThirdLibrary/MNN-master/build/libMNN.so
#8  0x00007ffff79cb447 in MNN::Interpreter::createMultiPathSession(std::vector<MNN::ScheduleConfig, std::allocator<MNN::ScheduleConfig> > const&) () at /home/white/ThirdLibrary/MNN-master/build/libMNN.so
#9  0x00007ffff79cbdc5 in MNN::Interpreter::createSession(MNN::ScheduleConfig const&) ()
    at /home/white/ThirdLibrary/MNN-master/build/libMNN.so
#10 0x0000555555570150 in SuperPoint::SuperPoint(char const*) (this=0x555555fe8f40, modelPath=0x555555572450 "/home/white/github/MNNSuperGlue/models/SuperPoint.mnn") at /home/white/github/MNNSuperGlue/src/superpoint.cpp:21
#11 0x0000555555568a6e in KeyPointsDetecter::KeyPointsDetecter(char const*, char const*, char const*) (this=0x7fffffffd6f0, superpoint_model_name=0x555555572450 "/home/white/github/MNNSuperGlue/models/SuperPoint.mnn", l2_model_name=0x555555572488 "/home/white/github/MNNSuperGlue/models/L2Norm.mnn", superglue_model_name=0x5555555724c0 "/home/white/github/MNNSuperGlue/models/SuperGlue.mnn")
    at /home/white/github/MNNSuperGlue/src/keypointdetecter.cpp:18
#12 0x0000555555565c1c in main() () at /home/white/github/MNNSuperGlue/main.cpp:19

---Original---
From: ***@***.***&gt;
Date: Thu, Jan 6, 2022 09:55 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Hanson0910/MNNSuperGlue] Segmentation fault when creatSession (Issue #5)




 是不是模型路径有问题，有绝对路径。
 
 
 | |
 Hanson
 |
 |
 ***@***.***
 |
 签名由网易邮箱大师定制
 On 1/5/2022 ***@***.***&gt; wrote：
 
 运行的时候，执行到SuperPoint的构造函数的this-&gt;session = this-&gt;net-&gt;createSession(this-&gt;config);这句报段错误，请问要怎么解决
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ironbrotherstyle** [comment]
> 模型路径没问题，SuperGlue和L2Norm都可以构造，而且路径有问题的话会报另一个错 方便的话，可以给个方便点的联系方式嘛，还有些其他问题想请教一下 这是gdb的调试信息： (gdb) bt #0 0x00007ffff63bda23 in __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:233 #1 0x00007ffff7b1e1a3 in std::_Function_handler<void (int), MNN::ConvolutionWinograd::onExecute(std::vector<MNN::Tensor*, std::allocator<MNN::Tensor*> > const&, std::vector<MNN::Tensor*, std::allocator<MNN::Tensor*> > const&)::{lambda(int)#2}>::_M_invoke(std::_Any_data const&, int&&) () at /home/white/ThirdLibrary/MNN-master/build/libMNN.so #2 0x00007ffff7affb0f in MNN::ThreadPool::enqueue(std::pair<std::function<void (int)>, int>&&, int) () at /home/white/ThirdLibrary/MNN-master/build/libMNN.so #3 0x00007ffff7b1f320 in MNN::ConvolutionWinograd::onExecute(std::vector<MNN::Tensor*, std::allocator<MNN::Tensor*> > const&, std::vector<MNN::Tensor*, std::allocator<MNN::Tensor*> > const&) () at /home/white/ThirdLibrary/MNN-master/build/libMNN.so #4 0x00007ffff7a0f068 in MNN::GeometryComputerUtils::shapeComputeAndGeometryTransform(std::vector<MNN::Schedule::PipelineInfo, std::allocator<MNN::Schedule::PipelineInfo> >&, MNN::GeometryComputer::Context&, std::shared_ptr<MNN::Backend>, MNN::Runtime::CompilerType) () at /home/white/ThirdLibrary/MNN-master/build/libMNN.so #5 0x00007ffff79db9cc in MNN::Pipeline::encode(bool, bool) () at /home/white/ThirdLibrary/MNN-master/build/libMNN.so #6 0x00007ffff79e31b7 in MNN::Session::resize(bool) () at /home/white/ThirdLibrary/MNN-master/build/libMNN.so #7 0x00007ffff79cb315 in MNN::Interpreter::createMultiPathSession(std::vector<M----Typ---Type <r---Type <r---T---T---Type <---T-------Type <return> to continue, or q <return> to quit--- NN::ScheduleConfig, std::allocator<MNN::ScheduleConfig> > const&, std::pair<std::map<MNNForwardType, std::shared_ptr<MNN::Runtime>, std::less<MNNForwardType>, std::allocator<std::pair<MNNForwardType const, std::shared_ptr<MNN::Runtime> > > >, std::shared_ptr<MNN::Runtime> > const&) () at /home/white/ThirdLibrary/MNN-master/build/libMNN.so #8 0x00007ffff79cb447 in MNN::Interpreter::createMultiPathSession(std::vector<MNN::ScheduleConfig, std::allocator<MNN::ScheduleConfig> > const&) () at /home/white/ThirdLibrary/MNN-master/build/libMNN.so #9 0x00007ffff79cbdc5 in MNN::Interpreter::createSession(MNN::ScheduleConfig const&) () at /home/white/ThirdLibrary/MNN-master/build/libMNN.so #10 0x0000555555570150 in SuperPoint::SuperPoint(char const*) (this=0x555555fe8f40, modelPath=0x555555572450 "/home/white/github/MNNSuperGlue/models/SuperPoint.mnn") at /home/white/github/MNNSuperGlue/src/superpoint.cpp:21 #11 0x0000555555568a6e in KeyPointsDetecter::KeyPointsDetecter(char const*, char const*, char const*) (this=0x7fffffffd6f0, superpoint_model_name=0x555555572450 "/home/white/github/MNNSuperGlue/models/SuperPoint.mnn", l2_model_name=0x555555572488 "/home/white/github/MNNSuperGlue/models/L2Norm.mnn", superglue_model_name=0x5555555724c0 "/home/white/github/MNNSuperGlue/models/SuperGlue.mnn") at /home/white/github/MNNSuperGlue/src/keypointdetecter.cpp:18 #12 0x0000555555565c1c in main() () at /home/white/github/MNNSuperGlue/main.cpp:19
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Thu, Jan 6, 2022 09:55 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [Hanson0910/MNNSuperGlue] Segmentation fault when creatSession (Issue #5) 是不是模型路径有问题，有绝对路径。 | | Hanson | | ***@***.*** | 签名由网易邮箱大师定制 On 1/5/2022 ***@***.***&gt; wrote： 运行的时候，执行到SuperPoint的构造函数的this-&gt;session = this-&gt;net-&gt;createSession(this-&gt;config);这句报段错误，请问要怎么解决 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt; — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你好，请问解决了吗，我也遇到了这个问题。

**Comment by olongo** [comment]
> 没解决，我后来把里面的用了pytorch原版的superpoint提点,然后用mnn的superglue匹配在cpu上可以跑，就是很慢

**Comment by olongo** [comment]
> > 模型路径没问题，SuperGlue和L2Norm都可以构造，而且路径有问题的话会报另一个错 方便的话，可以给个方便点的联系方式嘛，还有些其他问题想请教一下 这是gdb的调试信息： (gdb) bt #0 0x00007ffff63bda23 in __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:233 #1 0x00007ffff7b1e1a3 in std::_Function_handler<void (int), MNN::ConvolutionWinograd::onExecute(std::vector<MNN::Tensor*, std::allocatorMNN::Tensor* > const&, std::vector<MNN::Tensor*, std::allocatorMNN::Tensor* > const&)::{lambda(int)#2}>::_M_invoke(std::_Any_data const&, int&&) () at /home/white/ThirdLibrary/MNN-master/build/libMNN.so #2 0x00007ffff7affb0f in MNN::ThreadPool::enqueue(std::pair<std::function<void (int)>, int>&&, int) () at /home/white/ThirdLibrary/MNN-master/build/libMNN.so #3 0x00007ffff7b1f320 in MNN::ConvolutionWinograd::onExecute(std::vector<MNN::Tensor*, std::allocatorMNN::Tensor* > const&, std::vector<MNN::Tensor*, std::allocatorMNN::Tensor* > const&) () at /home/white/ThirdLibrary/MNN-master/build/libMNN.so #4 0x00007ffff7a0f068 in MNN::GeometryComputerUtils::shapeComputeAndGeometryTransform(std::vector<MNN::Schedule::PipelineInfo, std::allocatorMNN::Schedule::PipelineInfo >&, MNN::GeometryComputer::Context&, std::shared_ptrMNN::Backend, MNN::Runtime::CompilerType) () at /home/white/ThirdLibrary/MNN-master/build/libMNN.so #5 0x00007ffff79db9cc in MNN::Pipeline::encode(bool, bool) () at /home/white/ThirdLibrary/MNN-master/build/libMNN.so #6 0x00007ffff79e31b7 in MNN::Session::resize(bool) () at /home/white/ThirdLibrary/MNN-master/build/libMNN.so #7 0x00007ffff79cb315 in MNN::Interpreter::createMultiPathSession(std::vector<M----Typ---Type <r---Type <r---T---T---Type <---T-------Type  to continue, or q  to quit--- NN::ScheduleConfig, std::allocatorMNN::ScheduleConfig > const&, std::pair<std::map<MNNForwardType, std::shared_ptrMNN::Runtime, std::less, std::allocator<std::pair<MNNForwardType const, std::shared_ptrMNN::Runtime > > >, std::shared_ptrMNN::Runtime > const&) () at /home/white/ThirdLibrary/MNN-master/build/libMNN.so #8 0x00007ffff79cb447 in MNN::Interpreter::createMultiPathSession(std::vector<MNN::ScheduleConfig, std::allocatorMNN::ScheduleConfig > const&) () at /home/white/ThirdLibrary/MNN-master/build/libMNN.so #9 0x00007ffff79cbdc5 in MNN::Interpreter::createSession(MNN::ScheduleConfig const&) () at /home/white/ThirdLibrary/MNN-master/build/libMNN.so #10 0x0000555555570150 in SuperPoint::SuperPoint(char const*) (this=0x555555fe8f40, modelPath=0x555555572450 "/home/white/github/MNNSuperGlue/models/SuperPoint.mnn") at /home/white/github/MNNSuperGlue/src/superpoint.cpp:21 #11 0x0000555555568a6e in KeyPointsDetecter::KeyPointsDetecter(char const*, char const*, char const*) (this=0x7fffffffd6f0, superpoint_model_name=0x555555572450 "/home/white/github/MNNSuperGlue/models/SuperPoint.mnn", l2_model_name=0x555555572488 "/home/white/github/MNNSuperGlue/models/L2Norm.mnn", superglue_model_name=0x5555555724c0 "/home/white/github/MNNSuperGlue/models/SuperGlue.mnn") at /home/white/github/MNNSuperGlue/src/keypointdetecter.cpp:18 #12 0x0000555555565c1c in main() () at /home/white/github/MNNSuperGlue/main.cpp:19
> > […](#)
> > ---Original--- From: _**@**_._**> Date: Thu, Jan 6, 2022 09:55 AM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [Hanson0910/MNNSuperGlue] Segmentation fault when creatSession (Issue #5) 是不是模型路径有问题，有绝对路径。 | | Hanson | | _**@**_.*** | 签名由网易邮箱大师定制 On 1/5/2022 _**@**_._**> wrote： 运行的时候，执行到SuperPoint的构造函数的this->session = this->net->createSession(this->config);这句报段错误，请问要怎么解决 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: _**@**_.**_> — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 你好，请问解决了吗，我也遇到了这个问题。

没解决，我后来把里面的用了pytorch原版的superpoint提点,然后用mnn的superglue匹配在cpu上可以跑，就是很慢
